name: seed2ban
version: '${project.version}'
main: gg.corn.seed2ban.Seed2ban
api-version: 1.13

commands:
  seed2banreload:
    description: Reloads the configuration for seed2ban.
    permission: seed2ban.reload
    permission-message: You do not have permission!
    usage: /<command>

permissions:
  seed2ban.exempt:
    description: Exempts players from seed2ban's checks.
    default: op
  seed2ban.reload:
    description: Reloads the configuration for seed2ban.
    default: op